name: Azure Python 3.8

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Azure dependencies
      run: make install-azure

    - name: Lint with pylint
      run: make lint

    - name: Run tests with pytest
      run: make test

    - name: Format with black
      run: make format
